sudo: false

language: php

php:
  - 7.2
  - 7.3

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-text
